name: "Main"
on: pull_request # will trigger a GitHub Actions workflow on pull requests.
jobs:
  lint-and-test:
    name: Run linters and then tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # to get the latest code changes
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run ESLint
        run: pnpm run lint:scripts
      - name: Run Stylelint
        run: pnpm run lint:styles
      - name: Run Tests
        run: pnpm test
        env:
          CI: true
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          build: pnpm run build:vite
          start: pnpm run serve -- --port=5173
          wait-on: http://localhost:5173
          browser: chrome
          headless: true